import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./assets/plugins/custom/datatables/datatables.bundle.css";
import "./assets/plugins/custom/vis-timeline/vis-timeline.bundle.css";
import "./assets/plugins/global/plugins.bundle.css";
import "./assets/css/style.bundle.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
